# this package is internal. do not use it directly!
# required at least led_pin substitution defined.
substitutions:
  led_pin_inverted: "false"
  led_pin_ignore_strapping_warning: "false"

logger:
  logs:
    light: INFO
    status_led: INFO

light:
  - platform: status_led
    id: z_status_led
    name: Onboard LED
    icon: mdi:led-on
    internal: true
    entity_category: diagnostic
    pin:
      number: $led_pin
      inverted: $led_pin_inverted
      ignore_strapping_warning: $led_pin_ignore_strapping_warning
    effects:
      - lambda:
          name: fast_pulse
          update_interval: 0.1s
          lambda: |-
            static bool state = false;
            auto led = id(z_status_led);
            auto call = state ? led->turn_on() : led->turn_off();
            call.perform();
            state = !state;
      # - strobe:
      #     name: "fast_pulse"
      #     colors:
      #       - state: true
      #         duration: 0.1s
      #       - state: false
      #         duration: 0.1s


