substitutions:
  # Name of the node. Don't use underscores!
  # https://esphome.io/guides/faq.html#why-shouldn-t-i-use-underscores-in-my-device-name
  node_name: tion-3s
  # Name for the main entity and prefix for all others.
  friendly_name: $node_name
  # Change to sntp if you plan to use MQTT and tion_energy package.
  time_platform: homeassistant
  # UART configuration.
  # Make sure to use YOUR pins!
  tx_pin: TX
  rx_pin: RX
  baud_rate: "115200"
  # UART proxy configuration (optional).
  # Make sure to use YOUR pins!
  proxy_tx_pin: GPIO15
  proxy_rx_pin: GPIO13

  # WiFi settings.
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  # WiFi Access Point password.
  wifi_ap_password: tion-0123-3s

packages:
  tion:
    url: https://github.com/dentra/esphome-tion
    ref: 2024.8.0 # cant use substitutions here
    files:
      ## You can enable or disable some of the features listed below.
      ## The disabled feature starts with # symbol.
      ## The indentation before uncommented package is very important!

      ## Additional WiFi signal sensor.
      - packages/wifi_signal.yaml
      ## Additional Uptime sensor.
      - packages/uptime.yaml
      ## Additional Restart button.
      - packages/restart.yaml
      ## Unlock Tion 30°C heating.
      #- packages/tion_temperature30c.yaml
      ## Antifreeze protection. Automatically turns on the heater at a temperature of 0°C and below.
      - packages/tion_enable_antifreeze.yaml
      ## Common configuration settings. Do not comment or move or remove!
      - packages/base.yaml
      ## Change to esp32.yaml/esp32_s3.yaml/esp32_c3.yaml/esp32_s2.yaml to use with ESP32/ESP32-S3/C3/S2 chip.
      - packages/esp8266_uart.yaml
      ## Proxy internal Tion BLE module.
      #- packages/tion_3s_proxy.yaml
      ## Internal ESP32 temperature sensor.
      # - packages/esp32_temperature.yaml
      ## Lilygo T-Dongle S3 internal LED and button support
      # - packages/lilygo.yaml
      ## Web server support.
      # - packages/web_server.yaml
      ## Additional debug information.
      # - packages/debug.yaml

# Uncomment to enable MQTT connection.
# mqtt:
#   broker: !secret mqtt_broker
#   port: !secret mqtt_port
#   username: !secret mqtt_username
#   password: !secret mqtt_password
#   discovery: false # remove or set to true if you plan to use with Home Assistant

# Enable Home Assistant API connection. Please disable if you use MQTT
api:

# WiFi access point configuration.
wifi:
  # Comment next 2 lines to enable manual WiFi configuration via access point.
  ssid: $wifi_ssid
  password: $wifi_password
  # Comment next 2 lines to set access point without password.
  ap:
    password: $wifi_ap_password
  # To completely remove access point remove previous two lines and uncomment next one.
  #ap: !remove

# Virtual port configuration
vport:
  - platform: tion_3s_uart
    id: tion_uart_vport
    uart_id: tion_uart
    ## Optional, Interval between sending commands. Set to 0ms to send one command per loop.
    # command_interval: 20ms
    ## Optional, Command queue size. Default: 10.
    # command_queue_size: 16

# Main climate component configuration.
# See detailed description and additional parameters at CONFIGURATION.md
tion:
  type: 3s
  id: tion_api
  # Optional, use vport_id with multiple breezers.
  vport_id: tion_uart_vport
  # Optional, How often query device state. Default: 15s.
  update_interval: 15s
  # Optional, Timeout to combine update operations. Default: 200ms.
  batch_timeout: 200ms
  # Optional, Timeout to enable state problem sensor. Must be less than update_interval. Default: 3s.
  state_timeout: 3s
  # Optional, Updates sensor values on any state response or only if they have been changed. Default: false.
  force_update: false

  # Optional, Enable presets. Default: <empty> (no presets)
  # You can define any number of presets with any name.
  # In Home assistant climate entity presets with names home, away, boost, comfort,
  # eco, sleep and activity are automatically translated to your native language and assign icons.
  # Preset configuration:
  #  name_of_your_preset:
  #    fan_speed: 1            # remove or set to 0 to use current state
  #    temperature: 16         # remove or set to 0 to use current state
  #    heater: False           # remove to use current state
  #    power: True             #
  #    gate_position: outdoor  # remove to use current state, see below for available values
  # Available gate_position:
  #  * outdoor - set gate position to outdoor air intake (3S and 4S only)
  #  * indoor - set gate position to indoor air intake (3S and 4S only)
  #  * mixed - set gate position to mixed air intake (3S only)
  # Uncomment next 4 lines to enable example presets.
  # presets:
  #   home: { fan_speed: 2, temperature: 16, heater: False }
  #   away: { fan_speed: 1, temperature: 10, heater: False }
  #   sleep: { fan_speed: 1, temperature: 18 }

################################################################################
#
# Next sections set are only example configuration.
#
# In most cases it is enough, but if you prefer to customize please refer to
# CONFIGURATION.md for full set of available entities and options.
#
################################################################################

climate:
  - platform: tion
    id: tion_climate
    name: None # use friendly_name
    # add HEAT_COOL mode to support turn_on without touching current heater mode.
    enable_heat_cool: True

sensor:
  # Temperature of air before heater, °C (celsius).
  - platform: tion
    id: tion_outdoor_temperature
    type: outdoor_temperature
    name: Outdoor Temperature
  # Current productivity, m³/h (cubic meters per hour).
  - platform: tion
    id: tion_productivity
    type: productivity
    name: Productivity
  # Filter time left counter.
  - platform: tion
    id: tion_filter_time_left_days
    type: filter_time_left_days
    name: Filter Time Left
  # Boost time left sensor.
  - platform: tion
    id: tion_boost_time_left
    type: boost_time_left
    name: Boost Time Left

switch:
  # Buzzer control switch.
  - platform: tion
    id: tion_buzzer
    type: sound
    name: Buzzer
  # Boost/Turbo switch.
  - platform: tion
    id: tion_boost
    type: boost
    name: Boost
    # Optional, Heater state when boost enabled. If not set current state will be used.
    #heater: False
    # Optional, Target heater temperature state when boost enabled.
    #           If not set or set to 0 - current target temperature will be used.
    #temperature: 10

number:
  # Configure boost time.
  - platform: tion
    id: tion_boost_time
    type: boost_time
    name: Boost Time
    initial_value: 20min
    restore_value: true

select:
  # Optional, Air Intake control.
  - platform: tion
    id: tion_air_intake
    type: air_intake
    name: Air Intake

binary_sensor:
  # Informs about state receiving problem from the breezer.
  - platform: tion
    id: tion_state_problem
    type: state
    name: State Problem
  # Filter warning state.
  - platform: tion
    id: tion_filter_worn_out
    type: filter
    name: Filter Worn Out

text_sensor:
  # Tion firmware version.
  - platform: tion
    id: tion_firmware_version
    type: firmware_version
    name: Version
  # Reports Tion's errors (EC) and warnings (WS).
  - platform: tion
    id: tion_errors
    type: errors
    name: Errors

button:
  # Reset filter button.
  - platform: tion
    id: tion_reset_filter
    type: reset_filter
    name: Reset Filter
    # Reset filter confirmation. When off then reset_filter will not work.
    confirm:
      name: Reset Filter Confirm

