#!/bin/bash

prj_path=$(dirname $0)/..

# $prj_path/scripts/mk-config $1

types=(lt-ble 4s-ble 4s-uart 3s-ble 3s-uart o2-uart)

if [ "$1" != "" ]; then
  types=($*)
fi

prefix="configs/tion-"
suffix="-dev.yaml"

for br in "${types[@]}" ; do
  pushd $prj_path >/dev/null
  esphome config "${prefix}${br}${suffix}" >/dev/null
  res=$?
  popd >/dev/null
  if [ "$res" != "0" ]; then
    pushd $prj_path >/dev/null
    esphome config "${prefix}${br}${suffix}"
    popd >/dev/null
    exit $res
  fi
done

for br in "${types[@]}" ; do
  pushd $prj_path >/dev/null
  esphome compile "${prefix}${br}${suffix}"
  res=$?
  popd >/dev/null
  if [ "$res" != "0" ]; then
    exit $res
  fi
done
