#!/bin/bash

base_path=$(dirname $0)

version=master
if [ "$1" != "" ]; then
  version=$1
fi

types=(lt-ble 4s-ble 4s-uart 3s-ble 3s-uart)
for br in "${types[@]}" ; do
  parts=(${br//-/ })
  port=${parts[1]}
  type=${parts[0]}
  fn=$br;
  if [ "$port" == "ble" ]; then
    fn=$type
  else
    fn=$type-hw
  fi
  orig_fn=$fn
  if [ "$2" == "diff" ]; then
    fn=$fn-gen
  fi
  echo "Generating tion-$type config for $port connection..."
  jinja2 -Dversion=$version -Dport=$port -Dtype=$type $base_path/tion.yaml.j2 >tion-$fn.yaml
  if [ "$2" == "diff" ]; then
    diff tion-$fn.yaml $base_path/../tion-$orig_fn.yaml
  fi
done

