#!/bin/bash

prj_path=$(dirname $0)/..

vars=(
  node_add_mac_suffix=true
  tion_enable_heat_cool=true
  tion_energy=true
)

. $prj_path/scripts/j2_vars

br=4s-uart

tfn=$prj_path/tion.yaml.j2
ofn=tion-$br.yaml
dfn=${ofn%.*}-bin.${ofn##*.}

parts=(${br//-/ })
port=${parts[1]}
type=${parts[0]}


jinja2 $j2_vars -D port=$port -D type=$type -o $dfn $tfn $prj_path/scripts/j2_vars.yaml
  # -D project_source=./components \

pushd $prj_path >/dev/null
esphome compile $dfn
res=$?
popd >/dev/null
if [ "$res" != "0" ]; then
  exit $res
fi
