#!/bin/bash

prj_path=$(dirname $0)/..

if [ "$1" == "" ]; then
    echo "no version defined"
    exit 1
fi

. $prj_path/scripts/j2_vars

ofn=README.md
dfn=$ofn
if [ "$2" == "diff" ]; then
  dfn=/tmp/${ofn%.*}-gen.${ofn##*.}
fi

ofn=$prj_path/$ofn
tfn=$ofn.j2

jinja2 $j2_vars -o $dfn $tfn $prj_path/scripts/j2_vars.yaml

if [ "$2" == "diff" ]; then
  diff $dfn $ofn
  rm $dfn
fi
