substitutions:
  time_platform: homeassistant

time:
  - platform: $time_platform
    id: g_time

sensor:
  - platform: tion
    id: tion_power
    type: power

  - platform: total_daily_energy
    id: tion_daily_energy
    name: "Daily Energy"
    power_id: tion_power
    accuracy_decimals: 2
    entity_category: diagnostic
