#pragma once

#define TION_MIN_TEMPERATURE 1

#define TION_DEFAULT_MAX_TEMPERATURE 25
#ifndef TION_MAX_TEMPERATURE
#define TION_MAX_TEMPERATURE TION_DEFAULT_MAX_TEMPERATURE
#endif
#if TION_MAX_TEMPERATURE > 30 || TION_MAX_TEMPERATURE < 20
#define TION_MAX_TEMPERATURE TION_DEFAULT_MAX_TEMPERATURE
#endif

#ifndef TION_MAX_FAN_SPEED
#define TION_MAX_FAN_SPEED 6
#endif
